[project]
name = "deploy-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "salnavasilva@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "datasets>=5.0.1",
    "embetter[sentence-tfm]>=0.9.1",
    "numpy>=2.4.6",
    "pandas>=3.0.6",
    "pillow>=12.3.0",
    "scikit-learn>=1.9.1",
    "sentence-transformers>=6.1.0",
]

[project.scripts]
deploy-ml = "deploy_ml:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
